spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
#          uri: file://C:\Users\admin\IdeaProjects
          uri: https://github.com/jineey030/msaInflearn
          search-paths:
            - 'config-files'
            - '{application}'

server:
  port: 8888
